
drop table cashier;
drop table restaurant;
drop table inventory;
drop table chef;
drop table managers;
drop table customer;
drop table bill;
drop table waiter;
drop table item;
drop table contains;
drop table resorder;
drop table prepares;
drop table takenby;

CREATE TABLE 	RESTAURANT
(
	Name VARCHAR(40) NOT NULL,
	Address VARCHAR(40) NOT NULL,
	Cuisine VARCHAR(20),
	PRIMARY KEY (Name),
	UNIQUE (Address)
);

CREATE TABLE 	CHEF
(
	Res_Name VARCHAR(40) NOT NULL,
	ID_number CHAR(11) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Contact_Number CHAR(10) NOT NULL,
	Age INT NOT NULL ,
	Gender CHAR(1) NOT NULL,
	Address VARCHAR(70) NOT NULL,
	Salary INT NOT NULL ,
	Num_days_off INT NOT NULL,
	Working_time VARCHAR(12),
	PRIMARY KEY (ID_number),
	UNIQUE (Contact_Number),
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	MANAGERS
(
	Res_Name VARCHAR(40) NOT NULL,
	ID_number CHAR(11) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Contact_Number CHAR(10) NOT NULL,
	Age INT NOT NULL,
	Gender CHAR(1) NOT NULL,
	Address VARCHAR(40) NOT NULL,
	Salary INT NOT NULL,
	Num_days_off INT NOT NULL,
	Working_time VARCHAR(12),
	Chef_ID_number CHAR(11) NOT NULL,
	PRIMARY KEY (ID_number),
	UNIQUE (Contact_Number),
	FOREIGN KEY (Chef_ID_number) REFERENCES CHEF(ID_number) ON DELETE CASCADE,
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	INVENTORY
(
	Res_Name VARCHAR(40) NOT NULL,
	Item_code VARCHAR(5) NOT NULL,
	Item VARCHAR(90) NOT NULL,
	Quantity INT NOT NULL,
	ID_number CHAR(11) NOT NULL,
	PRIMARY KEY (Item_code), 
	FOREIGN KEY (ID_number) REFERENCES CHEF(ID_number) ON DELETE CASCADE,
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	RESORDER
(
	Res_Name VARCHAR(40) NOT NULL,
	Order_num INT NOT NULL,
	No_of_items VARCHAR(3) NOT NULL,
	PRIMARY KEY (Order_num),
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	ITEM
(
	Res_Name VARCHAR(40) NOT NULL,
	Item_Number INT NOT NULL,
	Description VARCHAR(40) NOT NULL,
	Quantity INT NOT NULL,
	Price INT NOT NULL,
	PRIMARY KEY (Item_Number),
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	CONTAINS
(
	Order_num INT NOT NULL,
	Item_Number INT NOT NULL,
	Quantity INT NOT NULL,
	PRIMARY KEY(Order_num,Item_Number),
	FOREIGN KEY (Order_num) REFERENCES RESORDER(Order_num) ON DELETE CASCADE,
	FOREIGN KEY (Item_Number) REFERENCES ITEM(Item_Number) ON DELETE CASCADE
);

CREATE TABLE 	PREPARES
(
	Order_num INT NOT NULL,
	ID_number CHAR(11) NOT NULL,
	PRIMARY KEY(Order_num,ID_number),
	FOREIGN KEY (Order_num) REFERENCES RESORDER(Order_num) ON DELETE CASCADE,
	FOREIGN KEY (ID_number) REFERENCES CHEF(ID_number) ON DELETE CASCADE
);

CREATE TABLE 	WAITER
(
	Res_Name VARCHAR(40) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	ID_number CHAR(11) NOT NULL,
	Contact_Number CHAR(10) NOT NULL,
	Age INT NOT NULL ,
	Gender CHAR(1) NOT NULL,
	Address VARCHAR(40) NOT NULL,
	Salary INT NOT NULL,
	Num_days_off INT NOT NULL,
	Working_time VARCHAR(12),
	PRIMARY KEY (ID_number),
	UNIQUE (Contact_Number),
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	TAKENBY
(
	Order_num INT NOT NULL,
	ID_number CHAR(11) NOT NULL,
	FOREIGN KEY (Order_num) REFERENCES RESORDER(Order_num) ON DELETE CASCADE,
	FOREIGN KEY (ID_number) REFERENCES WAITER(ID_number) ON DELETE CASCADE
);

CREATE TABLE 	CUSTOMER
(
	Res_Name VARCHAR(40) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	Cust_ID VARCHAR(11) NOT NULL,
	Contact_Number CHAR(10) NOT NULL,
	ID_number CHAR(11) NOT NULL,
	Order_num INT NOT NULL,
	PRIMARY KEY (Cust_ID),
	UNIQUE (Contact_Number),
	FOREIGN KEY (Order_num) REFERENCES RESORDER(Order_num) ON DELETE CASCADE,
	FOREIGN KEY (ID_number) REFERENCES WAITER(ID_number) ON DELETE CASCADE,
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE BILL
(
	Res_Name VARCHAR(40) NOT NULL,
	Bill_No INT NOT NULL,
	Total_Amount INT NOT NULL,
	Tax INT NOT NULL,
	Order_details VARCHAR(400) NOT NULL,
	Cust_ID VARCHAR(11) NOT NULL,
	PRIMARY KEY (Bill_No),
	FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER(Cust_ID) ON DELETE CASCADE,
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);

CREATE TABLE 	CASHIER
(
	Res_Name VARCHAR(40) NOT NULL,
	Name VARCHAR(20) NOT NULL,
	ID_number CHAR(11) NOT NULL,
	Contact_Number CHAR(10) NOT NULL,
	Age INT NOT NULL,
	Gender CHAR(1) NOT NULL,
	Address VARCHAR(40) NOT NULL,
	Salary INT NOT NULL,
	Num_days_off INT NOT NULL,
	Working_time VARCHAR(12),
	Bill_No INT,
	PRIMARY KEY (ID_number),
	UNIQUE (Contact_Number),
	FOREIGN KEY (Bill_No) REFERENCES BILL(Bill_No) ON DELETE CASCADE,
	FOREIGN KEY (Res_Name) REFERENCES RESTAURANT(Name) ON DELETE CASCADE
);



